// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oruhqqfphhfczreyfvoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ydWhxcWZwaGhmY3pyZXlmdm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDQ2OTMsImV4cCI6MjA2MTQ4MDY5M30.dXs7tAmidvwk1dJ5upGEpX8u0dEsF3OAThY7oUk-3bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);